name: Backup repo to GitLab
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backup-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push
        uses: ilkka/git-https-push-action@v1.1.0
        with:
          remoteUrl: ${{ secrets.GITLAB_URL }}


     
